services:
  db:
    image: postgres:14
    container_name: product_postgres
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass 
      POSTGRES_DB: product_db
    volumes:  
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - product_net 
    ports:
      - "5555:5432"

  product_service:
    build:
      context: ./
      dockerfile: ./Dockerfile 
    volumes:
      - ./:/app
    depends_on:
      - db 
    environment:
      DB_HOST: db 
      DB_PORT: 5432 
      DB_USER: product_user 
      DB_PASSWORD: product_pass
      DB_NAME: product_db 
    networks:
      - product_net 
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure

  migrate:
    image: migrate/migrate
    depends_on:
      - db 
    volumes:
      - ./db/migrations:/migrations 
    command: [
      "-path", "/migrations",
      "-database","postgres://product_user:product_pass@db:5432/product_db?sslmode=disable",
      "up"
    ]
    networks:
      - product_net

volumes:
  postgres_data:

networks:
  product_net:
