apiVersion: apps/v1

kind: Deployment 

metadata:
  name: product

spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    specs:
      containers:
        - name: rating
          image: Binit-Dhakal/product:1.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

      
