services:
  users_postgres:
    image: postgres:14
    container_name: users_postgres_db
    environment:
      POSTGRES_USER: users_service 
      POSTGRES_PASSWORD:  users_pass
      POSTGRES_DB: users_db
    volumes:  
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - users_net 
    ports:
      - "4444:5432"

  users_service:
    build:
      context: ./
      dockerfile: ./Dockerfile 
    volumes:
      - ./:/app
    depends_on:
      - users_postgres
    environment:
      DB_HOST: users_postgres 
      DB_PORT: 5432 
      DB_USER: users_service 
      DB_PASSWORD: users_pass 
      DB_NAME: users_db
    networks:
      - users_net 
    ports:
      - "8082:8082"
    deploy:
      restart_policy:
        condition: on-failure

  migrate:
    image: migrate/migrate
    depends_on:
      - users_postgres
    volumes:
      - ./db/migrations:/migrations 
      - ./db/wait-for-postgres.sh:/wait-for-postgres.sh
    entrypoint: ["/bin/sh", "/wait-for-postgres.sh", "users_postgres",
                 "migrate", "-path", "/migrations",
                 "-database", "postgres://users_service:users_pass@users_postgres:5432/users_db?sslmode=disable",
                 "up"]
    networks:
      - users_net

volumes:
  postgres_data:

networks:
  users_net:
